# Generated by Django 3.2.11 on 2025-06-21 14:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_thing'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='thing',
            table='core_thing',
        ),
    ]
