# Generated by Django 3.2.11 on 2025-06-21 15:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_thing_table'),
    ]

    operations = [
        migrations.CreateModel(
            name='Dependent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('katakana', models.CharField(blank=True, max_length=100, null=True, verbose_name='カタカナ')),
                ('name', models.CharField(blank=True, max_length=100, null=True, verbose_name='姓名')),
                ('relationship', models.CharField(blank=True, max_length=50, null=True, verbose_name='与本人关系')),
                ('birthday', models.DateField(blank=True, null=True, verbose_name='誕生日')),
                ('phone', models.CharField(blank=True, max_length=30, null=True, verbose_name='电话')),
                ('residence_card_number', models.CharField(blank=True, max_length=50, null=True, verbose_name='在留卡号')),
                ('status_of_residence', models.CharField(blank=True, max_length=50, null=True, verbose_name='在留资格')),
                ('residence_card_expiry', models.DateField(blank=True, null=True, verbose_name='在留有效期')),
                ('my_number', models.CharField(blank=True, max_length=50, null=True, verbose_name='マイナンバー')),
                ('basic_identity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dependents', to='core.basicidentity', verbose_name='所属客户')),
            ],
            options={
                'db_table': 'core_Dependent',
            },
        ),
    ]
