# Generated by Django 3.2.11 on 2024-06-14 23:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_vendor'),
    ]

    operations = [
        migrations.AddField(
            model_name='honkon_base',
            name='remarks',
            field=models.TextField(blank=True, null=True, verbose_name='备注'),
        ),
        migrations.AlterField(
            model_name='vendor',
            name='id',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
    ]
