# Generated by Django 3.2.11 on 2024-06-17 21:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_auto_20240614_2314'),
    ]

    operations = [
        migrations.CreateModel(
            name='reimburse',
            fields=[
                ('reimburse_id', models.AutoField(primary_key=True, serialize=False)),
                ('reimburse_date', models.DateField()),
                ('reimburse_subject', models.CharField(max_length=50)),
                ('reimburse_location', models.CharField(max_length=50)),
                ('reimburse_price', models.DecimalField(decimal_places=0, max_digits=10)),
                ('reimburse_details', models.CharField(max_length=50)),
                ('delete_flg', models.BooleanField(default=False, verbose_name='删除标志')),
            ],
        ),
    ]
