# Generated by Django 3.2.11 on 2024-06-17 22:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_reimburse'),
    ]

    operations = [
        migrations.CreateModel(
            name='funding',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('date', models.DateField()),
                ('subject', models.CharField(max_length=50)),
                ('price', models.DecimalField(decimal_places=0, max_digits=10)),
                ('delete_flg', models.BooleanField(default=False, verbose_name='删除标志')),
            ],
        ),
    ]
