# Generated by Django 3.2.11 on 2024-07-15 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_funding'),
    ]

    operations = [
        migrations.CreateModel(
            name='vehicle',
            fields=[
                ('vehicle_id', models.AutoField(primary_key=True, serialize=False)),
                ('vehicle_date', models.DateField()),
                ('vehicle_subject', models.CharField(max_length=50)),
                ('vehicle_location', models.CharField(max_length=50)),
                ('vehicle_price', models.DecimalField(decimal_places=0, max_digits=10)),
                ('vehicle_details', models.CharField(max_length=50)),
                ('delete_flg', models.BooleanField(default=False, verbose_name='删除标志')),
            ],
        ),
    ]
