# Generated by Django 3.2.11 on 2025-06-18 21:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0007_auto_20250618_2130'),
    ]

    operations = [
        migrations.RenameField(
            model_name='thing',
            old_name='cover',
            new_name='address',
        ),
        migrations.RenameField(
            model_name='thing',
            old_name='jiguan',
            new_name='customerType',
        ),
        migrations.RemoveField(
            model_name='thing',
            name='classification',
        ),
        migrations.RemoveField(
            model_name='thing',
            name='minzu',
        ),
        migrations.RemoveField(
            model_name='thing',
            name='sex',
        ),
        migrations.RemoveField(
            model_name='thing',
            name='sfz',
        ),
        migrations.RemoveField(
            model_name='thing',
            name='status',
        ),
        migrations.RemoveField(
            model_name='thing',
            name='tag',
        ),
        migrations.RemoveField(
            model_name='thing',
            name='xuehao',
        ),
        migrations.AddField(
            model_name='thing',
            name='companyName',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='thing',
            name='taxAdvisor',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='thing',
            name='name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='thing',
            name='remark',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
