# Generated by Django 3.2.11 on 2025-06-19 21:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0008_auto_20250618_2136'),
    ]

    operations = [
        migrations.CreateModel(
            name='BasicIdentity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('katakana', models.CharField(blank=True, max_length=100, null=True, verbose_name='カタカナ')),
                ('passport_number', models.CharField(blank=True, max_length=50, null=True, verbose_name='护照号')),
                ('name', models.CharField(blank=True, max_length=100, null=True, verbose_name='姓名')),
                ('birthday', models.DateField(blank=True, null=True, verbose_name='誕生日')),
                ('passport_expiry', models.DateField(blank=True, null=True, verbose_name='护照有效期')),
                ('phone', models.CharField(blank=True, max_length=30, null=True, verbose_name='电话')),
                ('postal_code', models.CharField(blank=True, max_length=20, null=True, verbose_name='郵便番号')),
                ('address', models.CharField(blank=True, max_length=255, null=True, verbose_name='住址')),
                ('residence_card_number', models.CharField(blank=True, max_length=50, null=True, verbose_name='在留卡号')),
                ('residence_card_expiry', models.DateField(blank=True, null=True, verbose_name='在留有效期')),
                ('my_number', models.CharField(blank=True, max_length=50, null=True, verbose_name='Mynumber')),
                ('entry_date', models.DateField(blank=True, null=True, verbose_name='入境时间')),
            ],
        ),
    ]
