# Generated by Django 3.2.11 on 2025-06-19 23:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0009_basicidentity'),
    ]

    operations = [
        migrations.RenameField(
            model_name='basicidentity',
            old_name='my_number',
            new_name='mynumber',
        ),
    ]
