# Generated by Django 3.2.11 on 2025-06-21 14:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0010_rename_my_number_basicidentity_mynumber'),
    ]

    operations = [
        migrations.DeleteModel(
            name='BasicIdentity',
        ),
    ]
